import type { Metadata } from 'next'
import { GeistSans } from 'geist/font'
import '../styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} bg-gradient-to-br from-primary-500 to-primary-400 h-screen text-white`}
      >
        {children}
      </body>
    </html>
  )
}
