export const githubUrl = 'https://github.com/charmingruby'
export const githubUsername = 'charmingruby'
export const linkedinUrl = 'https://www.linkedin.com/in/gustavo-dias21'
export const linkedinUsername = 'gustavo-dias21'
export const email = 'gustavodiasa2121@gmail.com'
